In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('news_category_dataset.csv')

In [3]:
df.head(5)

                                                text       category
0  CloudPeak launched a beta version of its weara...           tech
1  Lawmakers debated the proposed healthcare bill...       politics
2  Fans were thrilled as the actress revealed the...  entertainment
3  Developers praised the updated cloud platform ...           tech
4  The film festival award nominations were annou...  entertainment

##  Encode Labels 

Original notebook-এ ছিল:
```python
df['sentiment'].replace({'positive':1,'negative':0}, inplace=True)
```
এটা শুধু 2 label-এর জন্য কাজ করত। এখন 5 টা label আছে, তাই `LabelEncoder` ব্যবহার করছি — এটা automatically
যেকোনো সংখ্যক class handle করতে পারে (2 হোক বা 50)।

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['category_enc'] = le.fit_transform(df['category'])
print(le.classes_)

category_map = dict(enumerate(le.classes_))
print(category_map)

['business' 'entertainment' 'politics' 'sports' 'tech']
{0: 'business', 1: 'entertainment', 2: 'politics', 3: 'sports', 4: 'tech'}

In [8]:
df.head(5)

,text,category,category_enc
0,CloudPeak launched a beta version of its weara...,tech,4
1,Lawmakers debated the proposed healthcare bill...,politics,2
2,Fans were thrilled as the actress revealed the...,entertainment,1
3,Developers praised the updated cloud platform ...,tech,4
4,The film festival award nominations were annou...,entertainment,1

In [9]:
df.shape

(1100, 3)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   text          1100 non-null   object
 1   category      1100 non-null   object
 2   category_enc  1100 non-null   int32
dtypes: int32(1), object(2)
memory usage: 21.6+ KB

## Text Cleaning¶
1.Sample 10000 rows

2.Remove html tags

3.Remove special characters

4.Converting every thing to lower case

5.Removing Stop words

6.Stemming

In [12]:
import re 
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [13]:
df['text']=df['text'].apply(clean_html)

In [14]:
df.head(5)

,text,category,category_enc
0,CloudPeak launched a beta version of its weara...,tech,4
1,Lawmakers debated the proposed healthcare bill...,politics,2
2,Fans were thrilled as the actress revealed the...,entertainment,1
3,Developers praised the updated cloud platform ...,tech,4
4,The film festival award nominations were annou...,entertainment,1

In [15]:
# converting everything to lower

def convert_lower(text):
    return text.lower()

In [16]:
df['text']=df['text'].apply(convert_lower)

In [17]:
df.head(5)

,text,category,category_enc
0,cloudpeak launched a beta version of its weara...,tech,4
1,lawmakers debated the proposed healthcare bill...,politics,2
2,fans were thrilled as the actress revealed the...,entertainment,1
3,developers praised the updated cloud platform ...,tech,4
4,the film festival award nominations were annou...,entertainment,1

In [18]:
# function to remove special characters

def remove_special(text):
    x=''
    
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x + ' '
    return x

In [19]:
df['text']=df['text'].apply(remove_special)

In [20]:
df.head(5)

,text,category,category_enc
0,cloudpeak launched a beta version of its weara...,tech,4
1,lawmakers debated the proposed healthcare bill...,politics,2
2,fans were thrilled as the actress revealed the...,entertainment,1
3,developers praised the updated cloud platform ...,tech,4
4,the film festival award nominations were annou...,entertainment,1

In [21]:
# Remove the stop words
import nltk

In [22]:
from nltk.corpus import stopwords

In [23]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [24]:
def remove_stopwords(text):
    x=[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [25]:
df['text']=df['text'].apply(remove_stopwords)

In [26]:
df

,text,category,category_enc
0,"[cloudpeak, launched, beta, version, wearable,...",tech,4
1,"[lawmakers, debated, proposed, healthcare, bil...",politics,2
2,"[fans, thrilled, actress, revealed, trailer, u...",entertainment,1
3,"[developers, praised, updated, cloud, platform...",tech,4
4,"[film, festival, award, nominations, announced...",entertainment,1
...,...,...,...
1095,"[quantix, labs, unveiled, latest, cloud, platf...",tech,4
1096,"[central, bank, decided, hold, interest, rates...",business,0
1097,"[lawmakers, debated, proposed, immigration, bi...",politics,2
1098,"[election, commission, confirmed, results, ref...",politics,2
1099,"[stock, markets, rallied, today, investors, re...",business,0

In [27]:
# Perform stemming

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [28]:

def stem_words(text):
    y=[]
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [29]:
stem_words(['I','loved','loving','it'])

['i', 'love', 'love', 'it']

In [32]:
df['text']=df['text'].apply(stem_words)

In [33]:
df.head(5)

,text,category,category_enc
0,"[cloudpeak, launch, beta, version, wearabl, de...",tech,4
1,"[lawmak, debat, propos, healthcar, bill, heat,...",politics,2
2,"[fan, thrill, actress, reveal, trailer, upcom,...",entertainment,1
3,"[develop, prais, updat, cloud, platform, enhan...",tech,4
4,"[film, festiv, award, nomin, announc, music, l...",entertainment,1

In [34]:
# Join back

def join_back(list_input):
    return " ".join(list_input)

In [35]:
df['text']=df['text'].apply(join_back)

In [36]:
df.head(5)

,text,category,category_enc
0,cloudpeak launch beta version wearabl devic fe...,tech,4
1,lawmak debat propos healthcar bill heat parlia...,politics,2
2,fan thrill actress reveal trailer upcom music,entertainment,1
3,develop prais updat cloud platform enhanc came...,tech,4
4,film festiv award nomin announc music lead pack,entertainment,1

In [38]:
X=df.iloc[:,0:1].values
X

array([['cloudpeak launch beta version wearabl devic featur new batteri function'],
       ['lawmak debat propos healthcar bill heat parliamentari session'],
       ['fan thrill actress reveal trailer upcom music'],
       ...,
       ['lawmak debat propos immigr bill heat parliamentari session'],
       ['elect commiss confirm result referendum vote friday'],
       ['stock market ralli today investor react news inflat']],
      dtype=object)

In [39]:
X.shape

(1100, 1)

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500)

In [41]:
X=cv.fit_transform(df['text']).toarray()

In [42]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [43]:
X.shape

(1100, 308)

In [47]:
X[4].max()

1

In [48]:
y=df.iloc[:,-1].values

In [49]:
y

array([4, 2, 1, ..., 2, 2, 0])

In [50]:
y.shape

(1100,)

In [56]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y
)

In [57]:
X_train.shape

(880, 308)

In [58]:
X_test.shape

(220, 308)

In [59]:
y_train.shape

(880,)

In [60]:
y_test.shape

(220,)

In [61]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [62]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [63]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB()

In [64]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

In [65]:
y_test.shape

(220,)

In [66]:
y_pred1.shape

(220,)

In [67]:
from sklearn.metrics import accuracy_score

In [68]:
print("Gaussian",accuracy_score(y_test,y_pred1))
print("Multinomial",accuracy_score(y_test,y_pred2))
print("Bernaulli",accuracy_score(y_test,y_pred3))

Gaussian 1.0
Multinomial 1.0
Bernaulli 1.0

##  Predict on New Text (bonus — Original label-এ ফেরত আনতে `l লাগবে)

In [70]:
def predict_category(text, model=clf2):
    cleaned = join_back(stem_words(remove_stopwords(remove_special(convert_lower(clean_html(text))))))
    vec = cv.transform([cleaned]).toarray()
    pred_enc = model.predict(vec)
    return category_map[pred_enc[0]]

predict_category("The government passed a new tax bill in parliament today.")

'politics'

## cleaning → stopwords → stemming → CountVectorizer → train_test_split (stratified) → তিনটা Naive Bayes variant → accuracy_score, এই পুরো pipeline-এ কোনো bug বা data leakage নেই (train/test split আগে vectorize করে পরে split করলে leakage হতো, কিন্তু তোমারটা ঠিক আছে)।